# -*- coding: utf-8 -*-
"""Chat_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQsp-uc92DVj5YjzJAIkSwpIEJHM8jBm
"""

import openai
import os
from google.colab import userdata

# Fetch the API key from Colab secrets
openai.api_key = userdata.get('Rudra')

def ask_chatgpt(question):
    client = openai.OpenAI(api_key=openai.api_key) # Initialize the client with the API key
    response = client.chat.completions.create( # Use the updated method
        model="gpt-4o-mini", # Changed model to gpt-3.5-turbo
        messages=[{"role": "user", "content": question}],
        max_tokens=500
    )
    answer = response.choices[0].message.content # Access the content correctly
    return answer

while True:
    q = input("You: ")
    if q.lower() == "exit":
        break
    print("Bot:", ask_chatgpt(q))

